### PR TITLE
Add a little javascript on top of image display to make a list of job images to update.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/french-job-suggest/17)

### CODE REVIEW

**Comment by pcorpet** [comment]
+@dedan

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-:-KKTVorNO3EPjpQLvO28:-710483338)_

**Comment by pcorpet** [comment]
Demo link:
https://rawgit.com/bayesimpact/french-job-suggest/70c1329c7746c20a32a9238d96d4caed7b8196db/job-images.html

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-:-KKTZ6uySZDEqGYGgm8v:1789863405)_

**Comment by dedan** [comment]
:lgtm: I wrote a few comments, but feel free to also just ignore them, as this is a 'one off application'.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[job-images.html, line 46 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-KKgj0betI5jPknRvA7g:-KKgj0bfhgDBnrqJZJ4M:1996102663) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/70c1329c7746c20a32a9238d96d4caed7b8196db/job-images.html#L46)):_

> ``` HTML
>             '{{job.name}}',
>           link: function(scope, element, attrs) {
>             const job = scope.$eval('job')
> ```

Isn't there a nicer way to get the job from the scope? Hand it to the directive for example?

---

_[job-images.html, line 48 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-KKgj6Ni7N1NI3KwjQl3:-KKgj6Ni7N1NI3KwjQl4:-1103068694) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/70c1329c7746c20a32a9238d96d4caed7b8196db/job-images.html#L48)):_

> ``` HTML
>             const job = scope.$eval('job')
>               element.attr('title', job.name)
>               const children = element.children().children()
> ```

This directive assumes a lot about the structure of the HTML. Wouldn't it be better to use element IDs?

---

_[job-images.html, line 144 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-KKgjMV9NA7BR_FVJ6x1:-KKgjMV9NA7BR_FVJ6x2:-212718032) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/70c1329c7746c20a32a9238d96d4caed7b8196db/job-images.html#L144)):_

> ``` HTML
>   <body ng-controller="ImagesList">
>     <h1>Job Images</h1>
>     <fieldset ng-hide="jobs | filter: {needFix: true}: true | empty">
> ```

that's cool!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-:-KKgjROVAP1S6h5cilKp:320427679)_

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[job-images.html, line 46 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-KKgj0betI5jPknRvA7g:-KKh4MbyhUH42jKmQFLU:-97091983) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/70c1329c7746c20a32a9238d96d4caed7b8196db/job-images.html#L46)):_
<details><summary>

<i>Previously, dedan (Stephan Gabler) wrote…</i></summary>



> Isn't there a nicer way to get the job from the scope? Hand it to the directive for example?
> </details>
> I had made it explicit at the beginning, but it was reading `job="job"` and would force to create a new scope, without any clear gain.

---

_[job-images.html, line 48 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17#-KKgj6Ni7N1NI3KwjQl3:-KKh7ENkuw9BIg2aAOwY:341851711) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/70c1329c7746c20a32a9238d96d4caed7b8196db/job-images.html#L48)):_
<details><summary>

<i>Previously, dedan (Stephan Gabler) wrote…</i></summary>



> This directive assumes a lot about the structure of the HTML. Wouldn't it be better to use element IDs?
> </details>
> Not really, it assumes a lot about the HTML that it creates itself (see the template above). The trouble is that the jQuery lite embedded in Angular doesn't have selectors, so using classes is not an option, and for IDs, it's even more painful to create unique IDs.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/17)_

**Pull request merged**
