### PR TITLE
First setup: upload ROME "appellations" with minor cleanup.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/french-job-suggest/1) &emsp; Multiple assignees:&emsp;@dedan&nbsp;<a href="/bayesimpact/french-job-suggest/pulls/assigned/dedan">dedan</a>,&emsp;@florianjourda&nbsp;<a href="/bayesimpact/french-job-suggest/pulls/assigned/florianjourda">florianjourda</a>

### CODE REVIEW

**Comment by pcorpet** [comment]
+@dedan +@florianjourda 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1#-:-KEkWKtKVEJdkEEPBPAJ:793040211)_

**Comment by dedan** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[generate.sh, line 21 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1#-KEmUP8PenFFhw3MvTxZ:-KEmUP8PenFFhw3MvTx_:1683521274) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/e41842de0b48e3f44516ac87cd14120f58d15061/generate.sh#L21)):_
this does not work. Has to be `bin/upload.py`

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1#-KEmTbC8f18AAKycR6fA:-KEmTbC9xwgQzZLq4B37:-398697738) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/e41842de0b48e3f44516ac87cd14120f58d15061/README.md#L1)):_
The nested sentence sounds a bit clunky

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1)_

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[generate.sh, line 21 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1#-KEmUP8PenFFhw3MvTxZ:-KEmfl0Qw4ih_A-Sy7_s:-93196622) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/e41842de0b48e3f44516ac87cd14120f58d15061/generate.sh#L21)):_
Right. I now get the $DIR of generate.sh and use it for upload.py (so that the script also works outside of Docker).

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1#-KEmTbC8f18AAKycR6fA:-KEmftW6BFK3HnzqFNCA:-2015828356) ([raw file](https://github.com/bayesimpact/french-job-suggest/blob/e41842de0b48e3f44516ac87cd14120f58d15061/README.md#L1)):_
Split in 2 sentences.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1)_

**Comment by dedan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/french-job-suggest/1#-:-KEmjvfcxHMpKvKx4my5:1417088721)_

**Pull request merged**
